#!/usr/bin/env bash
set -euo pipefail

# git-diff-origin - Show diff between HEAD and its upstream tracking branch.

remote=$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}')
git diff "$remote"
