#!/usr/bin/env zsh
# git-nuke - Prune remotes and delete all local branches with no remote counterpart.
#
# # # # # # # # # # # # # # # # # #
# CAUTION: BEWARE OF THIS SCRIPT! #
# # # # # # # # # # # # # # # # # #
#
# This script prunes remote branches and
# deletes local branches with no remote counterpart
# INCLUDING UNMERGED BRANCHES WITH NO REMOTE
#
# This means that if you have an unmerged branch and
# someone deleted its remote counterpart for some reason
# without merging it first, YOU WILL LOSE YOUR WORK
#
# Beware that this script DELETES LOCAL BRANCHES
# WHICH HAVEN'T BEEN PUSHED YET.
# TODO: Add a --safe flag to avoid this

# Prune origin
echo "[git]: pruning..."
git fetch --prune

# Delete merged branches
echo "[git]: deleting merged branches..."
git branch --merged \
  | grep -v master \
  | grep -v '^\*' \
  | xargs git branch -d

# Delete unmerged branches with no remote counterpart
echo "[git]: deleting unmerged branches..."
git branch -avv \
  | awk '/: gone\]/ { print $1 }' \
  | xargs git branch -D

echo "\n\nI AM BECOME DEATH,\nDESTROYER OF WORLDS"
